### PR TITLE
Use `fetch_update` to support mock on 32-bit MIPS and ARMv5TE

### LINKED ISSUE #54: Does not build on MIPS and ARMv5
MIPS issue: https://github.com/metrics-rs/quanta/issues/22#issuecomment-914420194 , MIPS seems work before https://github.com/metrics-rs/quanta/pull/52

ARMv5(armv5te-unknown-linux-musleabi target) has the similar issue

```
error[E0599]: no method named `fetch_add` found for struct `Arc<AtomicCell<u64>>` in the current scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/quanta-0.9.2/src/mock.rs:48:21
   |
48 |         self.offset.fetch_add(amount.into_nanos());
   |                     ^^^^^^^^^ method not found in `Arc<AtomicCell<u64>>`

error[E0599]: no method named `fetch_sub` found for struct `Arc<AtomicCell<u64>>` in the current scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/quanta-0.9.2/src/mock.rs:53:21
   |
53 |         self.offset.fetch_sub(amount.into_nanos());
   |                     ^^^^^^^^^ method not found in `Arc<AtomicCell<u64>>`

error: aborting due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by messense**
Fixes #54.

### CODE REVIEW

**Comment by messense** [comment]
BTW I can also add arm/arm64 target to tests in this PR, or add them in a follow-up PR if you prefer.

**Comment by tobz** [comment]
I think the adding the tests here is correct/important, to make sure we're not regressing behavior again. 👍🏻

**Comment by tobz** [comment]
@messense Would you also want to change the MSRV from`1.45.0` to `1.51.0` in `.github/workflows/ci.yml`? Unrelated to your change, but apparently I missed that one of the dependencies started depending on a feature releases in 1.51.0.

**Comment by messense** [comment]
> @messense Would you also want to change the MSRV from `1.45.0` to `1.51.0` in `.github/workflows/ci.yml`? Unrelated to your change, but apparently I missed that one of the dependencies started depending on a feature releases in 1.51.0.

Done.

**Comment by messense** [comment]
nightly build issue https://github.com/tokio-rs/prost/issues/526

**Comment by messense** [comment]
It seems that prost 0.8.0 already fixed it. Nees https://github.com/metrics-rs/quanta/pull/49

**Comment by messense** [comment]
Looks like this `test_reference_self_calibration` test case is not very stable?

**Comment by tobz** [comment]
@messense Yeah, it's not super stable on virtual machines.  I think we can merge this PR given that it's just the self-calibration test that fails, and I can address the flakiness in another PR.

**Comment by tobz** [comment]
@messense Thanks again for your contribution.

**Comment by tobz** [comment]
@messense Published `quanta@v0.9.3` which includes this PR.

**Pull request merged**
